name: carp_mobile_sensing_app
description: The CARP Mobile Sensing App
version: 0.40.0
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/apps/carp_mobile_sensing_app
publish_to: 'none' 

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  # font_awesome_flutter: ^10.1.0

#  math:


  rosemary_maps:
    path: ./lib/rosemary_maps

  carp_serializable: ^1.0.0
  flutter_polyline_points: ^1.0.0
  carp_core: ^0.40.0      # the core CARP domain model
  carp_mobile_sensing: ^0.40.0
#  carp_connectivity_package: ^0.30.0  # conflict w. RP - different versions of rxdart
  carp_context_package: ^0.40.0
#  carp_audio_package: ^0.30.0
#  carp_communication_package: ^0.30.0
#  carp_apps_package: ^0.30.0
  carp_survey_package: ^0.40.0
#  research_package: ^1.2.1
  carp_polar_package: ^0.40.0
  carp_backend: ^0.40.0
  carp_webservices: ^0.40.0
#  carp_health_package: ^2.0.0
#  carp_firebase_backend: ^0.30.0

  # carp_esense_package: ^0.40.0
  # carp_movisens_package: ^0.32.0

#  research_package: ^0.9.3
  cupertino_list_tile: ^0.2.1
  google_maps_flutter: ^2.2.1
  # location: ^4.4.0
  # carp_background_location: ^3.0.1

  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 1.0.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 3.0.1
#  google_maps: 6.2.0

  google_maps_flutter_platform_interface: 2.2.1
  google_maps_flutter_web: 0.4.0+1
  intl: 0.17.0
  json_path: 0.4.1
  page_transition: 2.0.4
  percent_indicator: 4.2.2
  shared_preferences: 2.0.15
  timeago: 3.2.2
  url_launcher: 6.1.5
  flutter_animarker: ^3.2.0

# Overriding carp libraries to use the local copy
dependency_overrides:
#  carp_core:
#    path: ../../carp_core/
#  carp_mobile_sensing:
#    path: ../../carp_mobile_sensing/
#  carp_context_package:
#    path: ../../packages/carp_context_package/
#  carp_connectivity_package:
#    path: ../../packages/carp_connectivity_package/
#  # due to version conflict in device_calendar this cannot be included for now
#  # carp_communication_package:
#  #   path: ../../packages/carp_communication_package/
#  carp_audio_package:
#    path: ../../packages/carp_audio_package/
#  carp_apps_package:
#    path: ../../packages/carp_apps_package/
#  carp_esense_package:
#    path: ../../packages/carp_esense_package/
#  carp_polar_package:
#    path: ../../packages/carp_polar_package/
#  # esense_flutter:
#  #   path: ../../../../flutter-plugins/packages/esense_flutter/
#  carp_backend:
#    path: ../../backends/carp_backend/
#  carp_webservices:
#    path: ../../backends/carp_webservices/
#  # research_package:
#  #   path: ../../../../research.package/


dev_dependencies:
  test: any 
  lints: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# Is used to change the default app launch icons on iOS and Android.
# To install:
#  1. import the 'flutter_launcher_icons' package above
#  2. add the 'flutter_icons:' section below
#  3. run 'flutter pub get'
#  3. run 'flutter pub pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: "assets/cachet_logo.png"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
#    - assets/study.png
#    - assets/cachet_logo.png
#    - assets/logo.png
#    - assets/genderIcon.png
#    - assets/ageIcon.png
#    - assets/heightIcon.png
#    - assets/weightIcon.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
